// Native ESLint 9 flat config.
// eslint-config-next v14 is incompatible with ESLint 9 (uses deprecated
// context.getAncestors / getScope APIs and @rushstack/eslint-patch).
// We replicate the essential rules using ESLint-9-compatible plugin versions
// already present in the workspace root.

import tseslint from "../../node_modules/@typescript-eslint/eslint-plugin/dist/index.js";
import tsParser from "../../node_modules/@typescript-eslint/parser/dist/index.js";
import reactHooks from "../../node_modules/eslint-plugin-react-hooks/index.js";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Flat-config `files` patterns resolve against the *cwd*, not this file. ESLint
 * is invoked both from this directory (`npm run lint`) and from the repo root
 * (lint-staged, CI), so app-relative patterns must match either way. The `**\/`
 * prefix can match zero directories, so one pattern covers both.
 *
 * @param {string} pattern - Path relative to `apps/interface`.
 */
const glob = (pattern) => `**/${pattern}`;

const dummyPlugin = (ruleNames) => ({
  rules: Object.fromEntries(
    ruleNames.map((name) => [name, { create: () => ({}) }]),
  ),
});

/** @type {import("eslint").Linter.Config[]} */
const eslintConfig = [
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      "react-hooks": reactHooks,
      "@next/next": dummyPlugin(["no-img-element", "no-html-link-for-pages"]),
      "jsx-a11y": dummyPlugin(["media-has-caption"]),
    },
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "off",
    },
  },

  // Generated by `npm run codegen` — regenerate rather than hand-fix. The
  // graphql-request plugin emits an `any` in its SdkFunctionWrapper boilerplate
  // that we can't configure away; call sites in client.ts stay fully typed.
  {
    files: [glob("src/lib/graphql/generated.ts")],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

  // ── no-console, scoped to production source ─────────────────────────────────
  // Everything under src/ ships in the browser bundle, so debug logging there
  // would leak internal state to a real user's console. Diagnostics must go
  // through `@/lib/logger`, which silences debug/info in production builds.
  // `warn`/`error` stay allowed: they surface problems operators need to see.
  {
    files: [glob("src/**/*.{ts,tsx}")],
    rules: {
      "no-console": ["error", { allow: ["warn", "error"] }],
      "no-debugger": "error",
    },
  },

  // ── Exemptions ──────────────────────────────────────────────────────────────
  // Tests, mocks and dev/ops tooling never reach a production browser console.
  // `src/lib/analytics/run-job.ts` is a containerised job entrypoint whose
  // documented contract is to write JSON to stdout for k8s log collection.
  {
    files: [
      "**/*.test.{ts,tsx}",
      "**/*.spec.{ts,tsx}",
      "**/__tests__/**/*.{ts,tsx}",
      "**/__mocks__/**/*.{ts,tsx}",
      glob("jest.setup.ts"),
      glob("jest.polyfills.ts"),
      glob("vitest.setup.ts"),
      glob("scripts/**/*.{ts,tsx}"),
      glob("src/lib/analytics/run-job.ts"),
    ],
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
];

export default eslintConfig;
